name: Backup Routine
on:
  schedule:
    # Runs every hour, for now, just to trigger it once
    - cron: "30 * * * *"
jobs:
  backup-dataset:
    runs-on: ubuntu-latest
    name: Backup dataset
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Export dataset
        uses: sanity-io/github-action-sanity@v0.7-alpha
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
          NEXT_PUBLIC_SANITY_DATASET: ${{ secrets.NEXT_PUBLIC_SANITY_DATASET }}
        with:
          args: dataset export ${{ secrets.NEXT_PUBLIC_SANITY_DATASET }} backups/backup.tar.gz
      - name: Upload backup.tar.gz
        uses: actions/upload-artifact@v4
        with:
          name: backup-tarball
          path: backups/backup.tar.gz
          # Fails the workflow if no files are found; defaults to 'warn'
          if-no-files-found: error
